### ISSUE TITLE
Trouble Connecting To AWS MSK Running 	2.3.1

### ISSUE THREAD

**Issue by jeffdonovan1969** [pulumi/pulumi-kafka#12]
Hi,

I am running an AWS MSK cluster with Apache Kafka version 2.3.1.

While running the pulumi-kafka it is having trouble connecting to the brokers to create a topic.

Any ideas what is going wrong with the connection? We have the security group at allow all traffic (for the time being). Not sure why the 
read: connection reset by peer

Creating topic:{ topicName: 'healthCheckTopic', partitions: 3, replicationFactor: 3 }
[TRACE] [Sarama]2020/03/16 16:50:40 Initializing new client[TRACE] [Sarama]2020/03/16 16:50:40 client/metadata fetching metadata for all topics from broker b-2.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092
[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-2.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:49490->10.161.0.235:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:49490->10.161.0.235:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-3.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092
[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-3.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:38442->10.161.0.196:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:38442->10.161.0.196:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-1.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092
[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-1.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:46766->10.161.0.218:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:46766->10.161.0.218:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata no available broker to send metadata request to[TRACE] [Sarama]2020/03/16 16:50:41 client/brokers resurrecting 3 dead seed brokers
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata retrying after 250ms... (3 attempts remaining)[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-2.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092
[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-2.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:49498->10.161.0.235:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:49498->10.161.0.235:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-3.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092
[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-3.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:38450->10.161.0.196:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:38450->10.161.0.196:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-1.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092
[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-1.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:46774->10.161.0.218:9092: read: connection reset by p[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:46774->10.161.0.218:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata no available broker to send metadata request to
[TRACE] [Sarama]2020/03/16 16:50:41 client/brokers resurrecting 3 dead seed brokers
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata retrying after 250ms... (2 attempts remaining)
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-2.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092
[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-2.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:49522->10.161.0.235:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:49522->10.161.0.235:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-3.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092
[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-3.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:38474->10.161.0.196:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:38474->10.161.0.196:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-1.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-1.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:46798->10.161.0.218:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:46798->10.161.0.218:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata no available broker to send metadata request to[TRACE] [Sarama]2020/03/16 16:50:41 client/brokers resurrecting 3 dead seed brokers
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata retrying after 250ms... (1 attempts remaining)[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-2.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092
[TRACE] [Sarama]2020/03/16 16:50:41 Failed to connect to broker b-2.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092: read tcp 172.17.0.3:49528->10.161.0.235:9092: read: connection reset by peer[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata got error from broker -1 while fetching metadata: read tcp 172.17.0.3:49528->10.161.0.235:9092: read: connection reset by peer
[TRACE] [Sarama]2020/03/16 16:50:41 client/metadata fetching metadata for all topics from broker b-3.msk-ip-dev-validation.bqabnn.c5.kafka.us-east-1.amazonaws.com:9092

**Comment by leezen** [comment]
Any chance you could provide more details? Just looking at the trace output, it looks like you're trying to go from one RFC1918 ip range into another RFC1918 range. Are those networks bridged in any way to talk to one another?

**Comment by NamalaR1** [comment]
@leezen : yes those vpcs are connected via amazon transit gateway

**Comment by jeffdonovan1969** [comment]
I was wondering if you know of any issues trying to create topics in an AWS MSK? I am wondering if MSK supports all of the kafka operations that the package is trying to call.

**Comment by leezen** [comment]
This is the upstream provider used by this package: https://github.com/Mongey/terraform-provider-kafka - which in turn uses the Sarama client (https://github.com/Shopify/sarama) -- so it shouldn't be using the Kafka CLI to my knowledge. And hence, the Sarama log lines you see above. But looking at the log lines, it certainly looks like some kind of network configuration issue more than anything else? Have you tried manually talking to MSK from the 172.17.0.0/16 network?

**Comment by NamalaR1** [comment]
yes. we used kafka binaries to test the connectivity and it works..it just fails to run using pulumi code

**Comment by leezen** [comment]
Could you please share how your provider is configured?

**Comment by jeffdonovan1969** [comment]
Yes. 
Our config is set as:
config:
  aws:region: us-east-1
  kafka:bootstrapServers: [b-2.msk-ip-dev-validation.rig63h.c5.kafka.us-east-1.amazonaws.com:9092,b-1.msk-ip-dev-validation.rig63h.c5.kafka.us-east-1.amazonaws.com:9092,b-3.msk-ip-dev-validation.rig63h.c5.kafka.us-east-1.amazonaws.com:9092]

**Comment by jeffdonovan1969** [comment]
And the pertinent code is:

let pulumiTopic = 
                new kafka.Topic("topic", {
                    name: topic.topicName,
                    config: {
                        "name": topic.topicName,
                        "cleanup.policy": "compact",
                        "segment.ms": "20000"
                    },
                    partitions: topic.partitions,
                    replicationFactor: topic.replicationFactor
            });

**Comment by leezen** [comment]
Sorry I've not been more helpful here. It looks like the Pulumi code is working fine -- ultimately, it's using the provider, which uses the Sarama client to talk to Kafka. One thing I'm wondering is how the configuration of your provider compares to the parameters you've passed to the kafka binaries you used to test?

**Comment by jeffdonovan1969** [comment]
Thanks for your response, so there should be no problem using with Apache Kafka version 2.3.1?

**Comment by leezen** [comment]
None that I'm aware of. Going to close this issue for now.

**Comment by jeffdonovan1969** [comment]
Hi- One last question:

Can the package communicate to kafka brokers using plain text, tls, or both?
How can I tell the package what to use?

**Comment by leezen** [comment]
I'm not super familiar with the underlying client library, Sarama. The properties are all exposed via the provider interface: https://www.pulumi.com/docs/reference/pkg/nodejs/pulumi/kafka/#ProviderArgs

I would expect to set `saslMechanism` to `plain` and `tlsEnabled` to `false`.

**Comment by jeffdonovan1969** [comment]
Got it working thanks for your help. For reference the MSK/kafka cluster was expecting plain text so I had to set the following properties:
kafka:skipTlsVerify: true
  kafka:tlsEnabled: false
