### ISSUE TITLE
AIVEN kafkaUser missing import example

### ISSUE THREAD

**Issue by raphaelauv** [pulumi/pulumi-kafka#121]
File: [themes/default/content/registry/packages/aiven/api-docs/kafkauser/_index.md](https://www.pulumi.com/registry/packages/aiven/api-docs/kafkauser/)

**Comment by rquitales** [comment]
I believe this is now fixed: 
![Screenshot 2023-08-24 at 10 32 14 PM](https://github.com/pulumi/pulumi-kafka/assets/26103281/09752619-372e-4493-9205-16701c6bc2a1)
