### ISSUE TITLE
Error: tls: failed to parse private key

### ISSUE THREAD

**Issue by jeffdonovan1969** [pulumi/pulumi-kafka#15]
Hello,

I am running pulumi with kafka provider and trying to communicate with a AWS Managed Solution Kafka (MSK) cluster with TLS encryption.

I have the script working with plain text (no tls).

When I add TLS the script is failing with the following error:
error: tls: failed to parse private key

I am generating the key with OPEN SSL as:
openssl req -new -newkey rsa:2048 -days 365 -keyout healthcheck-producer.pem -out healthcheck-producer.csr

I creating a signed cert with csr file created above.

My provider config is set as:
config:
  aws:region: us-east-1
  kafka:skipTlsVerify: false
  kafka:tlsEnabled: true
  kafka:clientKey: ./config/ssl/healthcheck-producer.pem
  kafka:clientCert: ./config/ssl/healthcheck-producer-signed-cert.pem
  kafka:bootstrapServers: [b-2.msk-ip-dev-validation.xdgvci.c5.kafka.us-east-1.amazonaws.com:9094,b-1.msk-ip-dev-validation.xdgvci.c5.kafka.us-east-1.amazonaws.com:9094,b-3.msk-ip-dev-validation.xdgvci.c5.kafka.us-east-1.amazonaws.com:9094]

So do you have any ideas why I may be seeing this error message? What format for the private key is the provider expecting?

I have tls working with the same keys from a spring boot kafka client application.

Thanks for any insight you can give me.

**Comment by leezen** [comment]
Hello again! The underlying client for this provider uses `sarama`

You can see it loads the key like this: https://github.com/Shopify/sarama/blob/cb940f0f2a5e2ad97bd5d36c45cb6017a9a7eb66/tools/tls/config.go
and https://golang.org/pkg/crypto/tls/#LoadX509KeyPair describes the expected format.

I'd suggest double checking that you can load those files directly via the LoadX509KeyPair function as a first step in debugging.
