### ISSUE TITLE
Missing docs for `Acl` and `Topic`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-kafka#199]
### What happened?

As part of https://github.com/pulumi/pulumi-kafka/pull/195, we lost docs for the `Acl` and `Topic` resource.

### Expected Behavior

We don't loose docs on upgrades.

### Steps to reproduce

See upgrade

### Output of `pulumi about`

NA

### Additional context

It looks like the loss of docs was caused by https://github.com/Mongey/terraform-provider-kafka/commit/8b8961dcaa68d8b4089d6f905acaa9f972dd3715.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment]
I believe this is similar to https://github.com/pulumi/pulumi-spotinst/issues/366. Something in upstream docsgen we're not responding to correctly.

**Comment by guineveresaenger** [comment]
This was fixed, likely via the refactor of handling Examples sections, via upgrade to https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/v3.77.0 in https://github.com/pulumi/pulumi-kafka/pull/362. 🎉 

See our docs on the registry: https://www.pulumi.com/registry/packages/kafka/api-docs/topic/
