### ISSUE TITLE
Missing environment variables for KAFKA_CA_CERT, KAFKA_CLIENT_CERT and KAFKA_CLIENT_KEY

### ISSUE THREAD

**Issue by ffortier** [pulumi/pulumi-kafka#314]
### What happened?

As specified in the terraform plugin, it is possible to use those env variables to configure the provider: `KAFKA_CA_CERT`, `KAFKA_CLIENT_CERT` and `KAFKA_CLIENT_KEY`. When specified, it works, but I get the following warnings

> warning: provider config warning: This parameter is now deprecated and will be removed in a later release, please use `client_key` instead.
> warning: provider config warning: This parameter is now deprecated and will be removed in a later release, please use `ca_cert` instead.
> warning: provider config warning: This parameter is now deprecated and will be removed in a later release, please use `client_cert` instead.

### Example

export KAFKA_CA_CERT="$PWD/.local/int.crt"
export KAFKA_CLIENT_CERT="$PWD/.local/admin.crt"
export KAFKA_CLIENT_KEY="$PWD/.local/admin.key"

pulumi up

### Output of `pulumi about`

Logged in to Franciss-MacBook-Pro.local as Francis.Fortier (file://~)
CLI          
Version      3.90.1
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME    VERSION
kafka   3.5.0
python  unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in python: executable='/nix/store/9mp1h1bi1l6bd15bqwpd0mf57gyz1brd-python3-3.11.5/bin/python3' version='3.11.5'

Current Stack: organization/kafka.deploy.acls/nonprod

TYPE                    URN
pulumi:pulumi:Stack     urn:pulumi:nonprod::kafka.deploy.acls::pulumi:pulumi:Stack::kafka.deploy.acls-nonprod
pulumi:providers:kafka  urn:pulumi:nonprod::kafka.deploy.acls::pulumi:providers:kafka::default_3_5_0

Found no pending operations associated with nonprod

Backend        
Name           Franciss-MacBook-Pro.local
URL            file://~
User           Francis.Fortier
Organizations  
Token type     personal

Dependencies:
NAME          VERSION
pip           23.3.2
pulumi_kafka  3.5.0
setuptools    69.0.3
wheel         0.42.0

Pulumi locates its logs in /tmp by default
Logged out of file://~

### Additional context

It seems like it's missing the `defaultInfo/environment` section for the `config/variables/caCert`, `config/variables/clientCert` and `config/variables/clientKey` in https://github.com/pulumi/pulumi-kafka/blob/master/provider/cmd/pulumi-resource-kafka/schema.json

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @ffortier. Thanks for letting us know about this.
