### ISSUE TITLE
Supporting the sasl mechanism oauthbearer

### ISSUE THREAD

**Issue by kmdlcp** [pulumi/pulumi-kafka#323]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Kafka supports oauthbearer as one of its sasl mechanisms to use for authentication. To be able to use the Kafka provider together with such a Kafka cluster it also needs to be supported by the provider.

**Comment by iwahbe** [comment]
Hi @kmdlcp. Thanks for opening an issue. This provider is bridged from [github.com/Mongey/terraform-provider-kafka](https://github.com/Mongey/terraform-provider-kafka), so we support what they do for auth methods. https://github.com/Mongey/terraform-provider-kafka/pull/372 looks like it might add what you want, but I'm not 100% sure.

If it does, then we also support it in https://github.com/pulumi/pulumi-kafka/releases/tag/v3.6.0. If not, I recommend opening a ticked in [github.com/Mongey/terraform-provider-kafka](https://github.com/Mongey/terraform-provider-kafka).

**Comment by kmdlcp** [comment]
Hi @iwahbe 

Thanks for the quick response.
The pr does not add what i want. I took your suggestion and created a feature request in the terraform repo:

https://github.com/Mongey/terraform-provider-kafka/issues/377

**Comment by kmdlcp** [comment]
I have no created a pull request that includes what i need. Assuming that the PR will get approved, those changes to auth methods, should also end up reflecting in the pulumi provider. Correct?

PR: https://github.com/Mongey/terraform-provider-kafka/pull/379

**Comment by iwahbe** [comment]
We track upstream's releases, so as soon as they tag a release that includes your PR, we will release a new version of pulumi-kafka that also includes your fix.

**Comment by kmdlcp** [comment]
The PR has been completed.
Once you release a new version with terraform-provider-kafka v0.7.0, we cane close this issue as completed.

Any system as to when a new release is made?

**Comment by iwahbe** [comment]
The release was made yesterday: https://github.com/pulumi/pulumi-kafka/releases/tag/v3.7.0. It includes `terraform-provider-kafka v0.7.0`.
