### ISSUE TITLE
v3.6.0 incompatible with redpanda

### ISSUE THREAD

**Issue by mattfysh** [pulumi/pulumi-kafka#327]
### What happened?

After upgrading from 3.5.0 to 3.6.0 I started seeing this error, described in a terraform provider issue: https://github.com/Mongey/terraform-provider-kafka/issues/329

### Example

https://github.com/Mongey/terraform-provider-kafka/issues/329

### Output of `pulumi about`

CLI
Version 3.103.0
Go Version go1.21.5
Go Compiler gc

Host
OS debian
Version 12.4
Arch aarch64

Backend
Name sahara-ed94f00d-86876d5969-mfhkh
URL file:///data
User root
Organizations
Token type personal

### Additional context

Creating this issue here to track the upstream fix (https://github.com/Mongey/terraform-provider-kafka/pull/369) so it can be pulled into the pulumi provider once ready

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Thanks for tracking here. We will pull https://github.com/Mongey/terraform-provider-kafka/pull/369 in as soon as releases a patch.

**Comment by mattfysh** [comment]
The upstream fix has been merged, and should arrive in the next release: https://github.com/Mongey/terraform-provider-kafka/pull/393

**Comment by iwahbe** [comment]
v3.7.0 includes https://github.com/Mongey/terraform-provider-kafka/pull/393.

**Comment by mattfysh** [comment]
hey @iwahbe unfortunately the fix didn't make it into the v3.7.0 cut, but they've just released a v3.7.1 with the fix 🎁
