### ISSUE TITLE
kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

### ISSUE THREAD

**Issue by XBeg9** [pulumi/pulumi-kafka#39]
Latest 0.2.9 release from terraform-provider-kafka works as expected for me,

```tf
provider "kafka" {
  bootstrap_servers = ["*.*.*.*:9092"]
  tls_enabled       = false
  skip_tls_verify   = true
  sasl_username     = "test"
  sasl_password     = "test123"
  sasl_mechanism    = "plain"
}

resource "kafka_topic" "logs2" {
  name               = "systemd_logs2"
  replication_factor = 2
  partitions         = 1
}
```

but not pulumi-kafka@2.2.2":

```js
const provider = new kafka.Provider("kafka", {
  bootstrapServers: ["*.*.*.:9092"],
  saslMechanism: "plain",
  saslUsername: "test",
  saslPassword: "test123",
  skipTlsVerify: true,
  tlsEnabled: false,
});

const topic = new kafka.Topic(
  "demo",
  {
    name: "sample",
    replicationFactor: 2,
    partitions: 1,
  },
  { provider }
);
```

This gives me an error: 
```bash
	kafka:index:Topic (demo):
    	error: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)
```

**Comment by XBeg9** [comment]
@stack72 any updates?

**Comment by stack72** [comment]
To add a little more flavour to this bug, when the configuration is set to the pulumi stack file, then things work as expected

**Comment by XBeg9** [comment]
@stack72 yep, temporary `pulumi set config` fixes the problem for me.

**Comment by cakper** [comment]
Hello. I run into the same problem. Do you need any information from me to help with the fix?

**Comment by htthao** [comment]
Hi,

Does it have any update?
I try to set the config `pulumi config set --path kafka:bootstrapServers[0] "localhost:9092"`, but it still causes the problem.

**Comment by XBeg9** [comment]
@htthao I will try again if temp fix works, and will let you know.

**Comment by leezen** [comment]
I took a look recently and couldn't replicate this behavior with the `2.4.0` version of the `@pulumi/kafka` provider. The value passed via the provider configuration appears to work.

**Comment by htthao** [comment]
Hi,

I tried to add these configs and it worked:
`kafka:skipTlsVerify: "true"
  kafka:tlsEnabled: "false"`
Thanks for your support.
